# -*- coding: utf-8 -*-
"""How to Create an Awesome Mailing List for Your Call for Papers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3Cp8VqqYYQ2isl0KHt2tmbJuLBLsWmg
"""

import pandas as pd
import re

# aux function
def extract_emails(text):
    if isinstance(text, str):
        emails = re.findall(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', text)
        return emails
    else:
        text = str(text)  # Convert non-string inputs to string
        emails = re.findall(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', text)
        return emails

source = 'scopus' # 'scopus', 'wos'
file_path = ''

if source == 'wos':

    addresses_wos = pd.read_excel(file_path, usecols=["Email Addresses"])
    print(addresses_wos.shape)
    addresses_wos = addresses_wos.dropna()
    print(addresses_wos.shape)
    # addresses_wos
    addresses_wos['Emails'] = addresses_wos['Email Addresses'].str.split(';')
    addresses_wos = addresses_wos.explode('Emails')
    addresses_wos_final = list(addresses_wos['Emails'])

elif source == 'scopus':

    addresses_scopus = pd.read_csv(file_path, usecols=["Correspondence Address"])
    addresses_scopus['Emails'] = addresses_scopus['Correspondence Address'].apply(extract_emails)
    print(addresses_scopus)
    addresses_scopus = addresses_scopus.dropna()
    print(addresses_scopus)
    # addresses_scopus
    addresses_scopus = addresses_scopus.explode('Emails').reset_index(drop=True)
    addresses_scopus_final = list(addresses_scopus['Emails'])

# Convert to set for faster processing
addresses_wos_set = set(addresses_wos_final)
addresses_scopus_set = set(addresses_scopus_final)

# Find duplicates
duplicates = addresses_wos_set.intersection(addresses_scopus_set)

# Check if there are any duplicates
if duplicates:
    print("Duplicates found between addresses_wos and addresses_scopus:")
    print(duplicates)
else:
    print("No duplicates found between addresses_wos and addresses_scopus.")

unique_addresses = addresses_wos_set.union(addresses_scopus_set)

unique_addresses_list = list(unique_addresses)
len(unique_addresses_list)
unique_addresses_list = [str(email) for email in unique_addresses_list]

# Save the mailing list
file_path = "/content/unique_email_addresses.txt"

# salvataggio (; + a capo per semplicità)
with open(file_path, 'w') as file:
    for email in unique_addresses_list:
        file.write(email + ';' + '\n')

print("Unique email addresses saved to:", file_path)

